#!/bin/sh

echo "Run Formatter..."
pipenv run black --check server/ scripts/ tests/ config/ || { echo "unformatted files found"; exit 1; }


echo "Run Analyzer..."
pipenv run pylint --fail-under=10 server/ tests/
