FROM python:3.9.0-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    netcat \
    && rm -rf /var/lib/apt/lists/*

RUN pip install pipenv

WORKDIR /app

COPY Pipfile Pipfile.lock ./

RUN pipenv install --system --deploy --ignore-pipfile

COPY . .

CMD [ "/app/docker/scripts/entrypoint-prod.sh" ]
