"""preferences

Revision ID: c5f6c3002fb3
Revises: 47dd35321023
Create Date: 2022-01-18 19:34:43.927630

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c5f6c3002fb3'
down_revision = '47dd35321023'
branch_labels = None
depends_on = None


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preferences')
    # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preferences',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('preference_no', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('domain', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='preferences_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
