"""Form Questions

Revision ID: fa14feebca66
Revises: 30591b09199e
Create Date: 2022-01-16 09:27:53.469931

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa14feebca66'
down_revision = '70c4e432fde5'
branch_labels = None
depends_on = None


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    # ### end Alembic commands ###


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', mysql.VARCHAR(length=2000), nullable=True),
    sa.Column('is_subjective', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('options', sa.BLOB(), nullable=True),
    sa.Column('domain', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
