"""
feat: Add tshirts schema
Revision ID: 144964c5bf68
Revises: 5a408d60055d
Create Date: 2022-03-10 16:50:08.911554

"""
# pylint: skip-file

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "144964c5bf68"
down_revision = "5a408d60055d"
branch_labels = None
depends_on = None


def upgrade():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tshirts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("size", sa.Enum("S", "M", "L", "XL", "XXL"), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tshirts")
    # ### end Alembic commands ###
