"""
nullable dept_id in points
Revision ID: 15d5944dcba3
Revises: 89a8931a94c1
Create Date: 2022-03-21 14:05:40.533528

"""
# pylint: skip-file

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "15d5944dcba3"
down_revision = "89a8931a94c1"
branch_labels = None
depends_on = None


def upgrade():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "points",
        "department_id",
        existing_type=mysql.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "points", "department_id", existing_type=mysql.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
