"""
Nerdle and Guess Schema
Revision ID: 1fbe2aa05e3d
Revises: 144964c5bf68
Create Date: 2022-03-12 20:07:31.082017

"""
# pylint: skip-file

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1fbe2aa05e3d"
down_revision = "144964c5bf68"
branch_labels = None
depends_on = None


def upgrade():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guesses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guess", sa.String(length=5), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "nerdle",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("current_word", sa.String(length=100), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("streak", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nerdle")
    op.drop_table("guesses")
    # ### end Alembic commands ###
