"""
Add nerdle guess validation
Revision ID: 4b918666ec2a
Revises: 1fbe2aa05e3d
Create Date: 2022-03-13 06:06:29.392648

"""
# pylint: skip-file

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4b918666ec2a"
down_revision = "1fbe2aa05e3d"
branch_labels = None
depends_on = None


def upgrade():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "guesses", sa.Column("validation", sa.String(length=5), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("guesses", "validation")
    # ### end Alembic commands ###
