"""
add fcm token to user
Revision ID: 89a8931a94c1
Revises: f6d7284205c4
Create Date: 2022-03-19 19:10:46.473550

"""
# pylint: skip-file

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "89a8931a94c1"
down_revision = "f6d7284205c4"
branch_labels = None
depends_on = None


def upgrade():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("fcm_token", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "fcm_token")
    # ### end Alembic commands ###
