"""
domains table
Revision ID: 9ef7b81f0d4e
Revises: 71487ddd5473
Create Date: 2022-03-09 13:59:24.303020

"""
# pylint: skip-file

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9ef7b81f0d4e"
down_revision = "71487ddd5473"
branch_labels = None
depends_on = None


def upgrade():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "domains",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("domain", sa.String(length=20), nullable=True),
        sa.Column("description", sa.String(length=3000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("domains")
    # ### end Alembic commands ###
