"""
Events table
Revision ID: ba11687fdd5a
Revises: 9463b4735854
Create Date: 2022-03-09 14:02:09.461358

"""
# pylint: skip-file

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ba11687fdd5a"
down_revision = "9463b4735854"
branch_labels = None
depends_on = None


def upgrade():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("description", sa.String(length=3000), nullable=True),
        sa.Column("cluster_id", sa.Integer(), nullable=False),
        sa.Column("rules", sa.String(length=3000), nullable=True),
        sa.Column("form_link", sa.String(length=255), nullable=True),
        sa.Column("event_link", sa.String(length=255), nullable=True),
        sa.Column("image_link", sa.String(length=255), nullable=True),
        sa.Column("start_time", sa.String(length=25), nullable=True),
        sa.Column("end_time", sa.String(length=25), nullable=True),
        sa.Column("date", sa.String(length=25), nullable=True),
        sa.Column("is_reg_completed", sa.Boolean(), nullable=True),
        sa.Column("is_event_completed", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["cluster_id"],
            ["clusters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("events")
    # ### end Alembic commands ###
