"""
change type of start and end time
Revision ID: f6d7284205c4
Revises: 144964c5bf68
Create Date: 2022-03-18 18:42:37.124451

"""
# pylint: skip-file

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f6d7284205c4"
down_revision = "144964c5bf68"
branch_labels = None
depends_on = None


def upgrade():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "events",
        "start_time",
        existing_type=sa.VARCHAR(length=25),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "events",
        "end_time",
        existing_type=sa.VARCHAR(length=25),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.drop_column("events", "date")
    # ### end Alembic commands ###


def downgrade():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events", sa.Column("date", sa.VARCHAR(length=25), nullable=True)
    )
    op.alter_column(
        "events",
        "end_time",
        existing_type=sa.DateTime(),
        type_=sa.VARCHAR(length=25),
        existing_nullable=True,
    )
    op.alter_column(
        "events",
        "start_time",
        existing_type=sa.DateTime(),
        type_=sa.VARCHAR(length=25),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
