"""
Main constants
"""
# pylint: skip-file
from datetime import datetime

clusters = [
    {
        "id": 1,
        "name": "Arts",
        "image_link": "http://genericlink.com/route",
    },
    {
        "id": 2,
        "name": "Culturals",
        "image_link": "http://genericlink.com/route",
    },
    {
        "id": 3,
        "name": "Gaming",
        "image_link": "http://genericlink.com/route",
    },
    {
        "id": 4,
        "name": "Design and Media",
        "image_link": "http://genericlink.com/route",
    },
    {
        "id": 5,
        "name": "Hindi Lits",
        "image_link": "http://genericlink.com/route",
    },
    {
        "id": 6,
        "name": "English Lits",
        "image_link": "http://genericlink.com/route",
    },
    {
        "id": 7,
        "name": "Tamil Lits",
        "image_link": "http://genericlink.com/route",
    },
    {
        "id": 8,
        "name": "Telugu Lits",
        "image_link": "http://genericlink.com/route",
    },
]

events = [
    {
        "id": 1,
        "name": "Handiprint",
        "description": "Blindfolded Hand print painting",
        "cluster_id": 1,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 2,
        "name": "Lantern Designing",
        "description": "Lantern designing",
        "cluster_id": 1,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2022, 3, 27, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 3,
        "name": "Faciem",
        "description": "Traditional face painting",
        "cluster_id": 1,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2022, 3, 28, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 4,
        "name": "Origami Relay",
        "description": "Game Something",
        "cluster_id": 1,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 5,
        "name": "Departmental Wordilism",
        "description": "Participants would have to make an art with words embedded in it based on the theme provided to them by the organizers.",
        "cluster_id": 1,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 6,
        "name": "Wall Painting",
        "description": "The participants will be provided with a 2x2 m wall and they have to paint it.",
        "cluster_id": 1,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 7,
        "name": "Wealth from Waste",
        "description": "Offline 3-D modelling event using the junk and waste articles.",
        "cluster_id": 1,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 8,
        "name": "Photomontage",
        "description": "Making a collage using newspaper pieces on a white chart.",
        "cluster_id": 1,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 9,
        "name": "Dominoes",
        "description": "Creating the best domino effects.",
        "cluster_id": 1,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 10,
        "name": "Kite Making",
        "description": "Making a kite and decorating it based on the theme given.",
        "cluster_id": 1,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 11,
        "name": "Shadow Art",
        "description": "Making a formation of art out of its shadow.",
        "cluster_id": 1,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 12,
        "name": "Pointillism",
        "description": "participants will have to make an artwork filled with dots.",
        "cluster_id": 1,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 13,
        "name": "Melodiya",
        "description": "Singing-based event where the participant has to remake a song using the same lyrics but with a different tune",
        "cluster_id": 2,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 14,
        "name": "Dance Montage",
        "description": "Participants from each department must make a collage video where every video is of a freshers dancing to make a full length video",
        "cluster_id": 2,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 15,
        "name": "Utsav",
        "description": "Dance-based event in which a team has to come up with a good, themed script.",
        "cluster_id": 2,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 16,
        "name": "Channel Surfing",
        "description": "The event is an enactment of a person surfing TV channels on television.",
        "cluster_id": 2,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 17,
        "name": "Green Screen",
        "description": "One of the participants will be blindfolded, and a muted video will be played on the screen behind them. The other participant will have to guess the details of the video clip.",
        "cluster_id": 2,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 18,
        "name": "The Greatest Showman",
        "description": " Individual talent show for participants to express their unique talents that usually isn't performed in any cultural event.",
        "cluster_id": 2,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 19,
        "name": "Figurine Fest",
        "description": "A team event, that uses puppets & shadows/UV Light and perform using the given theme.",
        "cluster_id": 2,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 20,
        "name": "Choreonite solo conventional",
        "description": "ChoreoNite is a dance event where the performances is solo based on conventional music",
        "cluster_id": 2,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 21,
        "name": "Choreonite solo contemporary",
        "description": "ChoreoNite is a dance event where the performances is solo based on contemporary music",
        "cluster_id": 2,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 22,
        "name": "Choreonite solo classical",
        "description": "ChoreoNite is a dance event where the performances is solo based on classical music",
        "cluster_id": 2,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 23,
        "name": "Choreonite Western",
        "description": "ChoreoNite is a dance event where the performances is solo based on western music",
        "cluster_id": 2,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 24,
        "name": "Choreonite Duo",
        "description": "ChoreoNite is a dance event where the performances is duo based on various themes",
        "cluster_id": 2,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 25,
        "name": "Choreonite Group",
        "description": "ChoreoNite is a dance event where the performances is done by a group, based on various themes",
        "cluster_id": 2,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 26,
        "name": "Free Style (solo)",
        "description": "Free Style Dance battle",
        "cluster_id": 2,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 27,
        "name": "Dual Free Style",
        "description": "Free Style Dance battle",
        "cluster_id": 2,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 28,
        "name": "Manoranjan",
        "description": "",
        "cluster_id": 2,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 29,
        "name": "Battle of the Bands",
        "description": "A musical event where bands can perform original compositions, cover songs.",
        "cluster_id": 2,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 30,
        "name": "Vocals Solo Western",
        "description": "Grab the mic and express your vocal talents as you cover your favorite artists and make it your own.",
        "cluster_id": 2,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2022, 4, 4, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 31,
        "name": "Vocals Solo Eastern",
        "description": "Grab the mic and express your vocal talents as you cover your favorite artists and make it your own.",
        "cluster_id": 2,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2022, 4, 4, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 32,
        "name": "Vocals Solo Classical",
        "description": "Grab the mic and express your vocal talents as you cover your favorite artists and make it your own.",
        "cluster_id": 2,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 33,
        "name": "Vocals Duet Eastern",
        "description": "Grab the mic and express your vocal talents as you cover your favorite artists and make it your own.",
        "cluster_id": 2,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 34,
        "name": "Vocals Duet Western",
        "description": "Grab the mic and express your vocal talents as you cover your favorite artists and make it your own.",
        "cluster_id": 2,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 35,
        "name": "Vocals Solo Online",
        "description": "Grab the mic and express your vocal talents as you cover your favorite artists and make it your own.",
        "cluster_id": 2,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 36,
        "name": "Instrumentals Solo Classical",
        "description": "Showcase your exceptional instrumental skills as you rock the crowd with your divine instruments.",
        "cluster_id": 2,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 37,
        "name": "Instrumentals Solo Western",
        "description": "Showcase your exceptional instrumental skills as you rock the crowd with your divine instruments.",
        "cluster_id": 2,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 38,
        "name": "Instrumentals Duet",
        "description": "Showcase your exceptional instrumental skills as you rock the crowd with your divine instruments.",
        "cluster_id": 2,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 39,
        "name": "Act-A-Thon",
        "description": "Team will perform a mime act on stage based on the theme given to them on the spot. ",
        "cluster_id": 2,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 40,
        "name": "Movie Spoof",
        "description": "Teams choose an original scene from any movie and alter the style of presentation, props are prohibited.",
        "cluster_id": 2,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 41,
        "name": "Street Food Galore",
        "description": "Can you assert your supremacy in the kitchen? We'll be testing your cutlery skills ...",
        "cluster_id": 2,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 42,
        "name": "Valorant",
        "description": "An exciting 5v5 first person shooter game where 2 teams fight against to reign victorious!",
        "cluster_id": 3,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 43,
        "name": "Call of Duty Mobile",
        "description": "Multiplayer 5v5 mobile game where every team will face each other for glory",
        "cluster_id": 3,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 44,
        "name": "Rocket League",
        "description": "Multiplatform online game- A football match with cars ",
        "cluster_id": 3,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 45,
        "name": "BGMI",
        "description": "In BGMI we will be having battle royal mode where a squad will face each others",
        "cluster_id": 3,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 46,
        "name": "Just, the Nobody’s Game Part-1",
        "description": "Inspired by Netflix’s recent blockbuster, this is a serious game to play.....",
        "cluster_id": 3,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 47,
        "name": "Just, the Nobody’s Game Part-2",
        "description": "Inspired by Netflix’s recent blockbuster, this is a serious game to play.....",
        "cluster_id": 3,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 48,
        "name": "FRONTMAN",
        "description": "Creating a 2D character and showcasing it",
        "cluster_id": 4,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 49,
        "name": "10 FPS",
        "description": "Shooting a stop motion video in real life",
        "cluster_id": 4,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 50,
        "name": "Zoom-IN",
        "description": "Collage art-using Gallery view on Teams/Zoom/Gmeet",
        "cluster_id": 4,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 51,
        "name": "LOGO MAKING",
        "description": "Designing a logo for your department for NITTFEST",
        "cluster_id": 4,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 52,
        "name": "PROMO MAKING",
        "description": "Creating a promo video for your departmenr",
        "cluster_id": 4,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 53,
        "name": "SKETCH IT",
        "description": "Creating a digital comic panel",
        "cluster_id": 4,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 54,
        "name": "T-SHIRT DESIGNING",
        "description": "",
        "cluster_id": 4,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 55,
        "name": "MINI FILMOMANIA",
        "description": "Short film making",
        "cluster_id": 4,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 56,
        "name": "PHOTO MARATHON",
        "description": " 1 Day long Photography competition based on the given theme",
        "cluster_id": 4,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    # Hindi lits
    {
        "id": 57,
        "name": "JASHN-E-MAUSIQI",
        "description": "Quiz consisting of Hindi movies, songs and entertainment based general questions",
        "cluster_id": 5,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 58,
        "name": "JUGAL-BANDI",
        "description": "Present poem in harmony",
        "cluster_id": 5,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 59,
        "name": "VAD VIVAAD",
        "description": "Debate",
        "cluster_id": 5,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 60,
        "name": "SHABDJAAL",
        "description": "Crosswords and word search puzzles",
        "cluster_id": 5,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 61,
        "name": "DE DANA DAN",
        "description": "Questions testing cricket knowledge of participants ",
        "cluster_id": 5,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 62,
        "name": "TATKALIK BHASHAN",
        "description": "Impromptu Speech",
        "cluster_id": 5,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 63,
        "name": "HA HA KAR",
        "description": "Stand up comedy ",
        "cluster_id": 5,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 64,
        "name": "QUESTIONS ONLY",
        "description": "Participants will be provided  with topics. They'll have to ask question to each other related to the topic given to them. In response of the question there should be another question not a statement/ answer",
        "cluster_id": 5,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 65,
        "name": "NUKKAD NATAK",
        "description": "Street Play",
        "cluster_id": 5,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 66,
        "name": "KAWWALI",
        "description": "",
        "cluster_id": 5,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    # English lits
    {
        "id": 67,
        "name": "MAIN QUIZ",
        "description": "General english quiz",
        "cluster_id": 6,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 68,
        "name": "WHAT's THE GOOD WORD",
        "description": "Word related questions",
        "cluster_id": 6,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 69,
        "name": "JUST A MINUTE",
        "description": "An individual speaking event with 1 minute rounds.",
        "cluster_id": 6,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 70,
        "name": "SCRABBLE",
        "description": "",
        "cluster_id": 6,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 71,
        "name": "CHARADES",
        "description": "Dumb charades",
        "cluster_id": 6,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 72,
        "name": "EXTEMPORE",
        "description": "Speech based events involving shipwreck, etc",
        "cluster_id": 6,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 73,
        "name": "WAR OF WORDS",
        "description": "Debate",
        "cluster_id": 6,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 74,
        "name": "THE SUPERHERO CONUNDRUM",
        "description": "Creative writing event",
        "cluster_id": 6,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    # Tamil lits
    {
        "id": 75,
        "name": "ISAIYODU VILAIYAADU",
        "description": "Finding songs with the help of clues.",
        "cluster_id": 7,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 76,
        "name": "THIRAI THEDAL",
        "description": "Finding tamil cinema with the help of clues.",
        "cluster_id": 7,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 77,
        "name": "SOLLI ADI",
        "description": "Guessing words with the clues given by teammate, with some twists",
        "cluster_id": 7,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 78,
        "name": "KAVICHOLAI",
        "description": "poem contest",
        "cluster_id": 7,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 79,
        "name": "PATHIRIKAI",
        "description": "magazine making",
        "cluster_id": 7,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 80,
        "name": "TAMIL PAECHU ENGAL MOOCHU",
        "description": "Speech and debate contest",
        "cluster_id": 7,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 81,
        "name": "GALAGALA GALATA",
        "description": "comedy based drama event",
        "cluster_id": 7,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 82,
        "name": "KATHAI KATTU",
        "description": "Coming up with drama scripts and creative stories.",
        "cluster_id": 7,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    # Telugu lits
    {
        "id": 83,
        "name": "Cinema Sandhadi",
        "description": "Cinema based quiz",
        "cluster_id": 8,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 84,
        "name": "Sahithya Prashnavali",
        "description": "Literature based quiz",
        "cluster_id": 8,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 85,
        "name": "3! 2! 1!...Action",
        "description": "Dumb Charades",
        "cluster_id": 8,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 86,
        "name": "Telugu Kshanalu",
        "description": "just a minute contest",
        "cluster_id": 8,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 87,
        "name": "Padavinodam",
        "description": "Crossword based event",
        "cluster_id": 8,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
    {
        "id": 88,
        "name": "Chithra Katha",
        "description": "Story writing online event",
        "cluster_id": 8,
        "form_link": "http://genericlink.com/route",
        "rules": "",
        "event_link": "http://genericlink.com/route",
        "image_link": "http://genericlink.com/route",
        "start_time": datetime(2012, 3, 3, 10, 10, 10),
        "end_time": datetime(2012, 3, 3, 10, 10, 10),
        "date": "date",
        "is_reg_completed": False,
        "is_event_completed": False,
    },
]

points = [
    {
        "point": 5,
        "position": 1,
        "event_id": 1,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 1,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 1,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 2,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 2,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 2,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 3,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 3,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 3,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 4,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 4,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 4,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 1,
        "event_id": 5,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 2,
        "event_id": 5,
        "department_id": None,
    },
    {
        "point": 1,
        "position": 3,
        "event_id": 5,
        "department_id": None,
    },
    {
        "point": 8,
        "position": 1,
        "event_id": 6,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 2,
        "event_id": 6,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 3,
        "event_id": 6,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 7,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 7,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 7,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 8,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 8,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 8,
        "department_id": None,
    },
    {
        "point": 8,
        "position": 1,
        "event_id": 9,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 2,
        "event_id": 9,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 3,
        "event_id": 9,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 10,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 10,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 10,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 1,
        "event_id": 11,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 2,
        "event_id": 11,
        "department_id": None,
    },
    {
        "point": 1,
        "position": 3,
        "event_id": 11,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 1,
        "event_id": 12,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 2,
        "event_id": 12,
        "department_id": None,
    },
    {
        "point": 1,
        "position": 3,
        "event_id": 12,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 1,
        "event_id": 13,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 2,
        "event_id": 13,
        "department_id": None,
    },
    {
        "point": 1,
        "position": 3,
        "event_id": 13,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 14,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 14,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 14,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 15,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 15,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 15,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 16,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 16,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 16,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 17,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 17,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 17,
        "department_id": None,
    },
    {
        "point": 8,
        "position": 1,
        "event_id": 18,
        "department_id": None,
    },
    {
        "point": 6,
        "position": 2,
        "event_id": 18,
        "department_id": None,
    },
    {
        "point": 4,
        "position": 3,
        "event_id": 18,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 19,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 19,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 19,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 20,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 20,
        "department_id": None,
    },
    {
        "point": 1,
        "position": 3,
        "event_id": 20,
        "department_id": None,
    },
    {
        "point": 8,
        "position": 1,
        "event_id": 20,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 2,
        "event_id": 21,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 3,
        "event_id": 21,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 22,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 22,
        "department_id": None,
    },
    {
        "point": 1,
        "position": 3,
        "event_id": 22,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 23,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 23,
        "department_id": None,
    },
    {
        "point": 1,
        "position": 3,
        "event_id": 23,
        "department_id": None,
    },
    {
        "point": 8,
        "position": 1,
        "event_id": 24,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 2,
        "event_id": 24,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 3,
        "event_id": 24,
        "department_id": None,
    },
    {
        "point": 12,
        "position": 1,
        "event_id": 25,
        "department_id": None,
    },
    {
        "point": 10,
        "position": 2,
        "event_id": 25,
        "department_id": None,
    },
    {
        "point": 8,
        "position": 3,
        "event_id": 25,
        "department_id": None,
    },
    {
        "point": 6,
        "position": 4,
        "event_id": 25,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 1,
        "event_id": 26,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 2,
        "event_id": 26,
        "department_id": None,
    },
    {
        "point": 1,
        "position": 3,
        "event_id": 26,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 1,
        "event_id": 27,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 2,
        "event_id": 27,
        "department_id": None,
    },
    {
        "point": 1,
        "position": 3,
        "event_id": 27,
        "department_id": None,
    },
    {
        "point": 12,
        "position": 1,
        "event_id": 28,
        "department_id": None,
    },
    {
        "point": 10,
        "position": 2,
        "event_id": 28,
        "department_id": None,
    },
    {
        "point": 8,
        "position": 3,
        "event_id": 28,
        "department_id": None,
    },
    {
        "point": 6,
        "position": 4,
        "event_id": 28,
        "department_id": None,
    },
    {
        "point": 12,
        "position": 1,
        "event_id": 29,
        "department_id": None,
    },
    {
        "point": 10,
        "position": 2,
        "event_id": 29,
        "department_id": None,
    },
    {
        "point": 8,
        "position": 3,
        "event_id": 29,
        "department_id": None,
    },
    {
        "point": 6,
        "position": 4,
        "event_id": 29,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 1,
        "event_id": 30,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 2,
        "event_id": 30,
        "department_id": None,
    },
    {
        "point": 1,
        "position": 3,
        "event_id": 30,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 1,
        "event_id": 31,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 2,
        "event_id": 31,
        "department_id": None,
    },
    {
        "point": 1,
        "position": 3,
        "event_id": 31,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 1,
        "event_id": 32,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 2,
        "event_id": 32,
        "department_id": None,
    },
    {
        "point": 1,
        "position": 3,
        "event_id": 32,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 33,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 33,
        "department_id": None,
    },
    {
        "point": 1,
        "position": 3,
        "event_id": 33,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 34,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 34,
        "department_id": None,
    },
    {
        "point": 1,
        "position": 3,
        "event_id": 34,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 35,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 35,
        "department_id": None,
    },
    {
        "point": 1,
        "position": 3,
        "event_id": 35,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 1,
        "event_id": 36,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 2,
        "event_id": 36,
        "department_id": None,
    },
    {
        "point": 1,
        "position": 3,
        "event_id": 36,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 1,
        "event_id": 37,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 2,
        "event_id": 37,
        "department_id": None,
    },
    {
        "point": 1,
        "position": 3,
        "event_id": 37,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 38,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 38,
        "department_id": None,
    },
    {
        "point": 1,
        "position": 3,
        "event_id": 38,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 39,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 39,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 39,
        "department_id": None,
    },
    {
        "point": 10,
        "position": 1,
        "event_id": 40,
        "department_id": None,
    },
    {
        "point": 7,
        "position": 2,
        "event_id": 40,
        "department_id": None,
    },
    {
        "point": 4,
        "position": 3,
        "event_id": 40,
        "department_id": None,
    },
    {
        "point": 12,
        "position": 1,
        "event_id": 41,
        "department_id": None,
    },
    {
        "point": 10,
        "position": 2,
        "event_id": 41,
        "department_id": None,
    },
    {
        "point": 8,
        "position": 3,
        "event_id": 41,
        "department_id": None,
    },
    {
        "point": 6,
        "position": 4,
        "event_id": 41,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 43,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 43,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 43,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 45,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 45,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 45,
        "department_id": None,
    },
    {
        "point": 10,
        "position": 1,
        "event_id": 42,
        "department_id": None,
    },
    {
        "point": 7,
        "position": 2,
        "event_id": 42,
        "department_id": None,
    },
    {
        "point": 4,
        "position": 3,
        "event_id": 42,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 44,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 44,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 44,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 1,
        "event_id": 46,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 2,
        "event_id": 46,
        "department_id": None,
    },
    {
        "point": 1,
        "position": 3,
        "event_id": 46,
        "department_id": None,
    },
    {
        "point": 6,
        "position": 1,
        "event_id": 47,
        "department_id": None,
    },
    {
        "point": 4,
        "position": 2,
        "event_id": 47,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 47,
        "department_id": None,
    },
    {
        "point": 8,
        "position": 1,
        "event_id": 48,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 2,
        "event_id": 48,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 3,
        "event_id": 48,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 1,
        "event_id": 49,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 2,
        "event_id": 49,
        "department_id": None,
    },
    {
        "point": 1,
        "position": 3,
        "event_id": 49,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 50,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 50,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 50,
        "department_id": None,
    },
    {
        "point": 8,
        "position": 1,
        "event_id": 51,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 2,
        "event_id": 51,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 3,
        "event_id": 51,
        "department_id": None,
    },
    {
        "point": 8,
        "position": 1,
        "event_id": 52,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 2,
        "event_id": 52,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 3,
        "event_id": 52,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 1,
        "event_id": 53,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 2,
        "event_id": 53,
        "department_id": None,
    },
    {
        "point": 1,
        "position": 3,
        "event_id": 53,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 54,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 54,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 54,
        "department_id": None,
    },
    {
        "point": 10,
        "position": 1,
        "event_id": 55,
        "department_id": None,
    },
    {
        "point": 7,
        "position": 2,
        "event_id": 55,
        "department_id": None,
    },
    {
        "point": 4,
        "position": 3,
        "event_id": 55,
        "department_id": None,
    },
    {
        "point": 10,
        "position": 1,
        "event_id": 56,
        "department_id": None,
    },
    {
        "point": 7,
        "position": 2,
        "event_id": 56,
        "department_id": None,
    },
    {
        "point": 4,
        "position": 3,
        "event_id": 56,
        "department_id": None,
    },
    {
        "point": 6,
        "position": 1,
        "event_id": 57,
        "department_id": None,
    },
    {
        "point": 4,
        "position": 2,
        "event_id": 57,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 57,
        "department_id": None,
    },
    {
        "point": 6,
        "position": 1,
        "event_id": 58,
        "department_id": None,
    },
    {
        "point": 4,
        "position": 2,
        "event_id": 58,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 58,
        "department_id": None,
    },
    {
        "point": 6,
        "position": 1,
        "event_id": 61,
        "department_id": None,
    },
    {
        "point": 4,
        "position": 2,
        "event_id": 61,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 61,
        "department_id": None,
    },
    {
        "point": 6,
        "position": 1,
        "event_id": 63,
        "department_id": None,
    },
    {
        "point": 4,
        "position": 2,
        "event_id": 63,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 63,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 59,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 59,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 59,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 62,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 62,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 62,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 60,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 60,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 60,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 64,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 64,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 64,
        "department_id": None,
    },
    {
        "point": 9,
        "position": 1,
        "event_id": 66,
        "department_id": None,
    },
    {
        "point": 7,
        "position": 2,
        "event_id": 66,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 3,
        "event_id": 66,
        "department_id": None,
    },
    {
        "point": 10,
        "position": 1,
        "event_id": 65,
        "department_id": None,
    },
    {
        "point": 8,
        "position": 2,
        "event_id": 65,
        "department_id": None,
    },
    {
        "point": 6,
        "position": 3,
        "event_id": 65,
        "department_id": None,
    },
    {
        "point": 8,
        "position": 1,
        "event_id": 67,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 2,
        "event_id": 67,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 3,
        "event_id": 67,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 68,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 68,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 68,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 69,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 69,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 69,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 70,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 70,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 70,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 71,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 71,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 71,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 72,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 72,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 72,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 73,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 73,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 73,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 1,
        "event_id": 74,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 2,
        "event_id": 74,
        "department_id": None,
    },
    {
        "point": 1,
        "position": 3,
        "event_id": 74,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 76,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 76,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 76,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 79,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 79,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 79,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 80,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 80,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 80,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 81,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 81,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 81,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 82,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 82,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 82,
        "department_id": None,
    },
    {
        "point": 6,
        "position": 1,
        "event_id": 75,
        "department_id": None,
    },
    {
        "point": 4,
        "position": 2,
        "event_id": 75,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 75,
        "department_id": None,
    },
    {
        "point": 6,
        "position": 1,
        "event_id": 77,
        "department_id": None,
    },
    {
        "point": 4,
        "position": 2,
        "event_id": 77,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 77,
        "department_id": None,
    },
    {
        "point": 6,
        "position": 1,
        "event_id": 78,
        "department_id": None,
    },
    {
        "point": 4,
        "position": 2,
        "event_id": 78,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 78,
        "department_id": None,
    },
    {
        "point": 6,
        "position": 1,
        "event_id": 77,
        "department_id": None,
    },
    {
        "point": 4,
        "position": 2,
        "event_id": 77,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 77,
        "department_id": None,
    },
    {
        "point": 6,
        "position": 1,
        "event_id": 83,
        "department_id": None,
    },
    {
        "point": 4,
        "position": 2,
        "event_id": 83,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 83,
        "department_id": None,
    },
    {
        "point": 6,
        "position": 1,
        "event_id": 77,
        "department_id": None,
    },
    {
        "point": 4,
        "position": 2,
        "event_id": 77,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 77,
        "department_id": None,
    },
    {
        "point": 6,
        "position": 1,
        "event_id": 85,
        "department_id": None,
    },
    {
        "point": 4,
        "position": 2,
        "event_id": 85,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 85,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 84,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 84,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 84,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 86,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 86,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 86,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 87,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 87,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 87,
        "department_id": None,
    },
    {
        "point": 5,
        "position": 1,
        "event_id": 88,
        "department_id": None,
    },
    {
        "point": 3,
        "position": 2,
        "event_id": 88,
        "department_id": None,
    },
    {
        "point": 2,
        "position": 3,
        "event_id": 88,
        "department_id": None,
    },
]

departments = [
    {"id": 1, "name": "AR", "description": "some generic description"},
    {"id": 2, "name": "CL", "description": "some generic description"},
    {"id": 3, "name": "CV", "description": "some generic description"},
    {"id": 4, "name": "CY", "description": "some generic description"},
    {"id": 5, "name": "CA", "description": "some generic description"},
    {"id": 6, "name": "CS", "description": "some generic description"},
    {"id": 7, "name": "EE", "description": "some generic description"},
    {"id": 8, "name": "EC", "description": "some generic description"},
    {"id": 9, "name": "HS", "description": "some generic description"},
    {"id": 10, "name": "IC", "description": "some generic description"},
    {"id": 11, "name": "ME", "description": "some generic description"},
    {"id": 12, "name": "MT", "description": "some generic description"},
    {"id": 13, "name": "PH", "description": "some generic description"},
    {"id": 14, "name": "PR", "description": "some generic description"},
    {"id": 15, "name": "MG", "description": "some generic description"},
    {"id": 16, "name": "MA", "description": "some generic description"},
    {"id": 17, "name": "EN", "description": "some generic description"},
]
